version: '3.8'

services:
  web:
    image: nodeimage
    container_name: web
    build: .
    ports:
      - 3001:3000
  mongo:
    image: mongo
    container_name: mymongo
    ports:
      - 27017:27017